apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: play-deals-backend
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares: play-deals-backend-redirect-https@kubernetescrd
spec:
  rules:
    - host: api.bag.gransoftware.de
      http:
        paths:
          - backend:
              service:
                name: bag-backend
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.bag.gransoftware.de
      secretName: k3s-contabo-tls
