apiVersion: v1
kind: Secret
metadata:
  name: sa-{{ .Values.serviceAccountName }}-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: sa-{{ .Values.serviceAccountName }}
type: kubernetes.io/service-account-token
