name: play-deals-backend 1.0 CD
on:
  push:
    tags:
      - '*'
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build Project with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

      - uses: extractions/setup-just@v1

      - name: Build and publish image with jib
        run: just build-push-image
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ github.token }}

  deploy_on_k8:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - uses: azure/setup-helm@v3

      - uses: azure/setup-kubectl@v3
        id: install
        name: Setup kubectl client

      - name: create KUBECONFIG
        run: |
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > kube-config;
          chmod 600 kube-config;
          echo "KUBECONFIG=$(pwd)/kube-config" >> "$GITHUB_ENV"

      - name: Deploy on k8
        run: |
          kubectl config current-context;
          just helm-upgrade;
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DASHBOARD: ${{ secrets.DASHBOARD }}
          DASHBOARD_USER: ${{ secrets.DASHBOARD_USER }}
          DASHBOARD_PASS: ${{ secrets.DASHBOARD_PASS }}


