name: play-deals-backend 1.0 CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build Project with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

      - name: Build and publish image with jib
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: MathieuSoysal/jib-container-publish.yml@v2.0.7
        with:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
          tag-name: ${{ github.sha }}
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          java-version: 17

