name: play-deals-backend 1.0 CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build Project with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

      - name: Build and publish image with jib
        #        if: ${{ github.ref == 'refs/heads/main' }}
        run: just build-push-image
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ github.token }}

      - uses: actions-hub/kubectl@master
        #        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: azure/setup-helm@v3
      - name: Deploy on k8
        #        if: ${{ github.ref == 'refs/heads/main' }}
        run: just helm-upgrade
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DASHBOARD: ${{ secrets.DASHBOARD }}
          DASHBOARD_USER: ${{ secrets.DASHBOARD_USER }}
          DASHBOARD_PASS: ${{ secrets.DASHBOARD_PASS }}


